let seedDeliveries = [
  {
    'model': 'Delivery',
    'documents':
    [{ "timeslotBegin": "2017-01-17T08:00:00Z", "timeslotEnd": "2017-01-17T08:30:00Z", "carrier": "Deutsche Post", "supplier": "Magna", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T08:30:00Z", "timeslotEnd": "2017-01-17T09:00:00Z", "carrier": "Schenker", "supplier": "Denso", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T09:00:00Z", "timeslotEnd": "2017-01-17T09:30:00Z", "carrier": "Kühne + Nagel ", "supplier": "Hyundai Mobis", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T09:30:00Z", "timeslotEnd": "2017-01-17T10:00:00Z", "carrier": "Dachser", "supplier": "Bridgestone", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T10:00:00Z", "timeslotEnd": "2017-01-17T10:30:00Z", "carrier": "Rhenus", "supplier": "Adient ", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T10:30:00Z", "timeslotEnd": "2017-01-17T11:00:00Z", "carrier": "IDS Logistik", "supplier": "Aisin", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T11:00:00Z", "timeslotEnd": "2017-01-17T11:30:00Z", "carrier": "Panalpina", "supplier": "Michelin", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T11:30:00Z", "timeslotEnd": "2017-01-17T12:00:00Z", "carrier": "UPS", "supplier": "Faurecia", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T12:00:00Z", "timeslotEnd": "2017-01-17T12:30:00Z", "carrier": "Logwin", "supplier": "ZF Friedrichshafen", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T12:30:00Z", "timeslotEnd": "2017-01-17T13:00:00Z", "carrier": "Rhenus", "supplier": "Goodyear", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T13:00:00Z", "timeslotEnd": "2017-01-17T13:30:00Z", "carrier": "Hellmann Worldwide Logistics", "supplier": "Lear Corporation", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T13:30:00Z", "timeslotEnd": "2017-01-17T14:00:00Z", "carrier": "TNT", "supplier": "TRW", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T14:00:00Z", "timeslotEnd": "2017-01-17T14:30:00Z", "carrier": "Hapag-Lloyd", "supplier": "Delphi", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T14:30:00Z", "timeslotEnd": "2017-01-17T15:00:00Z", "carrier": "Kühne + Nagel ", "supplier": "Valeo", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T15:00:00Z", "timeslotEnd": "2017-01-17T15:30:00Z", "carrier": "Dachser", "supplier": "Cummins", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T15:30:00Z", "timeslotEnd": "2017-01-17T16:00:00Z", "carrier": "Rhenus", "supplier": "Mahle", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T16:00:00Z", "timeslotEnd": "2017-01-17T16:30:00Z", "carrier": "Panalpina", "supplier": "Sumitomo Electric", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T16:30:00Z", "timeslotEnd": "2017-01-17T17:00:00Z", "carrier": "UPS", "supplier": "ThyssenKrupp Automotive", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T17:00:00Z", "timeslotEnd": "2017-01-17T17:30:00Z", "carrier": "DPD", "supplier": "Yazaki", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T17:30:00Z", "timeslotEnd": "2017-01-17T18:00:00Z", "carrier": "Fiege", "supplier": "Weichai Power", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T18:00:00Z", "timeslotEnd": "2017-01-17T18:30:00Z", "carrier": "Deutsche Bahn ", "supplier": "Schaeffler", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T18:30:00Z", "timeslotEnd": "2017-01-17T19:00:00Z", "carrier": "Kühne + Nagel ", "supplier": "Toyota Boshoku", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T19:00:00Z", "timeslotEnd": "2017-01-17T19:30:00Z", "carrier": "Dachser", "supplier": "Matsushita Electric", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T19:30:00Z", "timeslotEnd": "2017-01-17T20:00:00Z", "carrier": "IDS Logistik", "supplier": "Autoliv", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T20:00:00Z", "timeslotEnd": "2017-01-17T20:30:00Z", "carrier": "Panalpina", "supplier": "Tenneco", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T20:30:00Z", "timeslotEnd": "2017-01-17T21:00:00Z", "carrier": "Schenker", "supplier": "BorgWarner", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T21:00:00Z", "timeslotEnd": "2017-01-17T21:30:00Z", "carrier": "Kühne + Nagel ", "supplier": "Calsonic Kansei", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T21:30:00Z", "timeslotEnd": "2017-01-17T22:00:00Z", "carrier": "Dachser", "supplier": "Magneti Marelli", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] },
    { "timeslotBegin": "2017-01-17T22:00:00Z", "timeslotEnd": "2017-01-17T22:30:00Z", "carrier": "Rhenus", "supplier": "Hitachi", "yardDeliveries": [{ "quantity": 0, "yard": { "name": "Yard 1" } }, { "quantity": 0, "yard": { "name": "Yard 2" } }, { "quantity": 0, "yard": { "name": "Yard 3" } }, { "quantity": 0, "yard": { "name": "Express" } }] }]
  }
];

module.exports = seedDeliveries;